<?php
/**
 * Created by PhpStorm.
 * User: wq
 * Date: 2016/12/27
 * Time: 下午2:52
 */
namespace app\modules\frontend\controllers;

use yii\web\Controller;
use app\modules\frontend\models\User;
use Yii;

class IsloginController extends Controller {
    public function beforeAction($action)
    {
        $this->isLogin();
        return parent::beforeAction($action); // TODO: Change the autogenerated stub
    }

    public function isLogin() {
        $key = "session_id";
        $userKey = isset($_COOKIE[$key]) ? $_COOKIE[$key] : null;
        if ($userKey) {
            $userValue = Yii::$app->cache->get($userKey);
            if ($userValue) {
                $temp = explode("|", $userValue);
                if (isset($temp)) {
                    Yii::$app->session['username'] = $temp[0];
                    Yii::$app->session['uid'] = $temp[1];
                    return true;
                }
            }
        }
        setcookie($key, null);
        return $this->redirect(array('/frontend/login/login'))->send();
    }
}